meta_product_name: "Food trotter"
meta_title: "Food trotter - Eating IS visiting !"
meta_description: "Grâce à Food trotter, découvrez de nouveaux pays à travers leurs spécialités locales."
meta_image: "cover_picture.png" # should exist in `app/assets/images/`

